### ISSUE TITLE
The script can't retrive the access token

### ISSUE THREAD

**Issue by A3EKV** [shuichiro-makigaki/mendeley_cli#1]
Hello,
I have tried the mendeley-cli as per the instructions of README file. It launches the browser but nothing happens after that, I can see there is a code in the url but the webpage it redirects to doesn't exist. (I have used https://localhsot:8888).

I am using Python 3.8.10 on Ubuntu 20.04.
Any insights what's happening?
Thank you

**Comment by shuichiro-makigaki** [comment]
Ah, OK. Please use HTTP and localhost, instead of HTTPS and local**hsot** :)

**Comment by A3EKV** [comment]
Thank you!
the localhsot was a typo while I was writing the issue (my bad, I didn't use copy/paste).
When I change the protocol to http it worked.
But I wonder why is that the case? As far as I know (very limited knowledge)  the redirect_uri could be anything and it doesn't matter which protocol I use?

**Comment by shuichiro-makigaki** [comment]
In this script, the local server listens to HTTP only. So, the callback URL should be HTTP and localhost.
