### ISSUE TITLE
How to loop through the API pagination?

### ISSUE THREAD

**Issue by A3EKV** [shuichiro-makigaki/mendeley_cli#2]
Hi,
I have properly followed the instructions in the README file and everything works as expected.

```
mendeley get documents
```

However, the Mendeley API paginate the response to 20 entries. Is there a way to loop through all the pages in order to display all the documents.

**Comment by shuichiro-makigaki** [comment]
I fixed the problem at the latest release. Please update mendeley_cli via PIP.
